{
 "title": "MCC Ingress (Manage your civil cases)",
 "description": "MCC Ingress (Manage your civil cases)",
 "tags": [
  "system",
  "kubernetes",
  "ingress"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests, exported_namespace)"
    }
   },
   {
    "name": "ingress",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests{exported_namespace = \"$namespace\"}, ingress)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(nginx_ingress_controller_request_duration_seconds_count{exported_namespace = \"$namespace\", path !~\"/socket.io/.*\", ingress = \"$ingress\"}[1m])/2)",
     "legendFormat": "req / m"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(increase(nginx_ingress_controller_request_duration_seconds_sum{exported_namespace = \"$namespace\", path !~\"/socket.io/.*\", ingress = \"$ingress\"}[1m]) / increase(nginx_ingress_controller_request_duration_seconds_count{exported_namespace = \"$namespace\", path !~\"/socket.io/.*\", ingress = \"$ingress\"}[1m]) > 0)/2",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Request HTTP Codes",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (increase(nginx_ingress_controller_requests{exported_namespace = \"$namespace\", path !~\"/socket.io/.*\", ingress = \"$ingress\"}[1m]))/2"
    }
   ]
  },
  {
   "title": "Request HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(status) (increase(nginx_ingress_controller_requests{exported_namespace=\"$namespace\", path!~\"/socket.io/.*\", ingress=\"$ingress\", status=~\"4..|5..\"}[1m])) /2"
    }
   ]
  },
  {
   "title": "Pod counts by status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (phase) (kube_pod_status_phase{namespace=\"$namespace\",pod=~\"$ingress.*\"}) "
    }
   ]
  },
  {
   "title": "Request Duration Quantiles",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le) (increase(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace = \"$namespace\", path !~\"/socket.io/.*\", ingress = \"$ingress\"}[1m]))/2)",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (increase(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace = \"$namespace\", path !~\"/socket.io/.*\",ingress = \"$ingress\"}[1m]))/2)",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (increase(nginx_ingress_controller_request_duration_seconds_bucket{exported_namespace = \"$namespace\", path !~\"/socket.io/.*\", ingress = \"$ingress\"}[1m]))/2)",
     "legendFormat": "0.75"
    }
   ]
  }
 ]
}