name: Deploy with Helm

on:
  push:
    branches: ["**"]

permissions: {}

jobs:
  test-two:
    name: Test Workflow 2
    runs-on: ubuntu-latest
    steps:
      - name: Simple echo
        run: echo "This is a test workflow triggered on push to any branch."
