# Taken from https://github.com/ministryofjustice/devsecops-actions/tree/main/sca#quick-start---minimal-configuration
name: SCA
run-name: SCA - Software Composition Analysis

on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight UTC

  pull_request:
    branches: ["main"]

permissions: {}

jobs:
  sca:
    name: SCA - Software Composition Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: write
      pull-requests: write
      issues: write
      security-events: read

    steps:
      - name: Run, SCA - Software Composition Analysis
        uses: ministryofjustice/devsecops-actions/sca@86248cec9a6bb1fd4dabc08a05178e0650d3af4f # Feature branch
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

          # Custom Configuration - CodeQL wants to upload SARIF file and so does this workflow. Keeping CodeQL behaviour.
          codeql-upload-findings: "never"
          disable-yarn-audit: "true"