name: test workflow

on:
  push:
    branches: ["**"]

permissions: {}

jobs:
  test:
    name: Test Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Simple echo
        run: echo "This is a test workflow triggered on push to any branch."